services:
  api:
    build:
      context: ./vehicle-repair-API
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.12"
    container_name: api
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data/data.db
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-me}
      - ENV=${ENV:-dev}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS:-7}
    volumes:
      - ./vehicle-repair-API/app:/app/app:rw
      - ./vehicle-repair-API/migrations:/app/migrations:rw
      - ./vehicle-repair-API/alembic.ini:/app/alembic.ini:ro
      - ./vehicle-repair-API/data:/app/data:rw
    ports:
      - "8000:8000"
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  frontend:
    build:
      context: ./vehicle-repair-web
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      api:
        condition: service_healthy
    environment:
      VITE_API_URL: http://localhost:8000
    volumes:
      - ./vehicle-repair-web:/app:rw
      - /app/node_modules
    ports:
      - "5173:5173"
    command: ["pnpm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
