name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  api-tests:
    name: API Tests (Python)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vehicle-repair-API
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: vehicle-repair-API/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q

  web-tests:
    name: Web Tests (Node)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vehicle-repair-web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: vehicle-repair-web/package.json

      - name: Install
        run: npm ci || npm install

      - name: Lint
        run: npm run lint --if-present

      - name: Unit tests
        run: npm test --if-present -- --run

  docker-build:
    name: Build Docker images
    needs: [api-tests, web-tests]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API image
        uses: docker/build-push-action@v6
        with:
          context: ./vehicle-repair-API
          file: ./vehicle-repair-API/Dockerfile
          push: false
          tags: vehicle-repair/api:ci-${{ github.sha }}

      - name: Build Web image
        uses: docker/build-push-action@v6
        with:
          context: ./vehicle-repair-web
          file: ./vehicle-repair-web/Dockerfile
          push: false
          tags: vehicle-repair/web:ci-${{ github.sha }}

