name: Frontend Pages
on:
  push:
    branches: ['main']
    paths:
      - 'vehicle-repair-web/**'
      - '.github/workflows/frontend-pages.yml'
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vehicle-repair-web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: vehicle-repair-web/pnpm-lock.yaml
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true
      - name: Build
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
        run: pnpm build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: vehicle-repair-web/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

